# ── TERRAGON VALUE DISCOVERY CONFIGURATION ──
# Advanced Repository (82/100 maturity) - Optimization & Modernization Focus

repository:
  name: "agent-mesh-federated-runtime"
  maturity_level: "advanced"
  maturity_score: 82
  primary_language: "python"
  frameworks: ["fastapi", "pytorch", "libp2p", "grpc"]
  architecture_type: "distributed_p2p_mesh"

# Advanced Repository Scoring Weights
scoring:
  weights:
    advanced:
      wsjf: 0.5          # Weighted Shortest Job First
      ice: 0.1           # Impact, Confidence, Ease
      technicalDebt: 0.3  # Technical debt focus for advanced repos
      security: 0.1      # Security improvements
  
  thresholds:
    minScore: 15         # Higher threshold for advanced repos
    maxRisk: 0.7         # Accept moderate risk for high value
    securityBoost: 2.5   # High security priority
    complianceBoost: 2.0 # Compliance importance
    performanceBoost: 1.8 # Performance optimization focus

# Value Discovery Sources
discovery:
  sources:
    gitHistory:
      enabled: true
      depth: 100
      patterns: ["TODO", "FIXME", "HACK", "XXX", "DEPRECATED"]
    
    staticAnalysis:
      enabled: true
      tools:
        - name: "mypy"
          command: "mypy src/ --strict"
        - name: "bandit"
          command: "bandit -r src/"
        - name: "safety"
          command: "safety check"
        - name: "ruff"
          command: "ruff check src/"
    
    securityScanning:
      enabled: true
      tools:
        - "snyk"
        - "trivy"
        - "semgrep"
    
    performanceMonitoring:
      enabled: true
      baseline_file: "performance-regression.yml"
      threshold_degradation: 0.05
    
    dependencyAnalysis:
      enabled: true
      update_strategy: "security_first"
      outdated_threshold_days: 90

# Continuous Execution Configuration
execution:
  maxConcurrentTasks: 1
  
  testRequirements:
    minCoverage: 85
    performanceRegression: 5
    securityScanPass: true
    
  rollbackTriggers:
    - testFailure
    - buildFailure
    - securityViolation
    - performanceRegression
    
  automationLevel: "supervised" # autonomous, supervised, manual

# Advanced Repository Focus Areas
focus_areas:
  # Critical gaps identified in assessment
  critical:
    - "ci_cd_activation"
    - "core_implementation"
    - "security_integration"
    
  # High-value optimizations
  optimization:
    - "performance_tuning"
    - "architecture_modernization"
    - "technical_debt_reduction"
    - "monitoring_enhancement"
    
  # Innovation opportunities
  innovation:
    - "ai_ops_integration"
    - "edge_computing_optimization"
    - "chaos_engineering_enhancement"

# Value Tracking
metrics:
  track:
    - "deployment_frequency"
    - "lead_time_changes"
    - "mean_time_recovery"
    - "change_failure_rate"
    - "technical_debt_ratio"
    - "security_posture_score"
    - "performance_score"
    - "developer_productivity"
  
  reporting:
    format: "json"
    frequency: "daily"
    retention_days: 90

# Integration Settings
integrations:
  github:
    enabled: true
    auto_pr: true
    auto_merge: false
    pr_template: ".terragon/pr_template.md"
  
  monitoring:
    prometheus_endpoint: "http://localhost:9090"
    grafana_dashboard: true
  
  notifications:
    enabled: true
    channels: ["github_issues"]
    severity_threshold: "medium"

# Learning Configuration
learning:
  enable_feedback_loop: true
  model_update_frequency: "weekly"
  confidence_threshold: 0.8
  adaptation_rate: 0.1

# Advanced Automation Rules
automation_rules:
  # Auto-apply low-risk changes
  auto_apply:
    - type: "dependency_patch_update"
      risk_threshold: 0.2
    - type: "documentation_update"
      risk_threshold: 0.1
    - type: "test_addition"
      risk_threshold: 0.3
  
  # Auto-create PRs for medium-risk changes
  auto_pr:
    - type: "dependency_minor_update"
      risk_threshold: 0.5
    - type: "security_fix"
      risk_threshold: 0.6
    - type: "performance_optimization"
      risk_threshold: 0.4
  
  # Require manual review for high-risk changes
  manual_review:
    - type: "architecture_change"
      risk_threshold: 0.7
    - type: "breaking_change"
      risk_threshold: 0.8
    - type: "major_dependency_update"
      risk_threshold: 0.9