apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-mesh-hpa
  namespace: agent-mesh
  labels:
    app.kubernetes.io/name: agent-mesh
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: agent-mesh
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: network_connections_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 5
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agent-mesh-global-hpa
  namespace: agent-mesh
  labels:
    app.kubernetes.io/name: agent-mesh
    app.kubernetes.io/component: global-autoscaling
    deployment.type: global
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: agent-mesh
  minReplicas: 10  # Higher minimum for global deployment
  maxReplicas: 200  # Massive scale for global distribution
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # More conservative for global scale
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: External
    external:
      metric:
        name: global_request_rate
        selector:
          matchLabels:
            component: agent-mesh
      target:
        type: AverageValue
        averageValue: "1000"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120  # Slower scaling for stability
      policies:
      - type: Percent
        value: 50
        periodSeconds: 120
      - type: Pods
        value: 10
        periodSeconds: 120
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 600  # Very conservative scale down
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
      - type: Pods
        value: 5
        periodSeconds: 120
      selectPolicy: Min